// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsApplication.Data;

namespace SportsApplication.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20190715114353_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SportsApplication.Data.Entity.AllAthleteList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("athlete_name");

                    b.HasKey("id");

                    b.ToTable("AllAthleteLists");
                });

            modelBuilder.Entity("SportsApplication.Data.Entity.AthleteByTest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("athlete_distance");

                    b.Property<int>("athlete_id");

                    b.Property<int>("test_id");

                    b.HasKey("id");

                    b.ToTable("AthleteByTests");
                });

            modelBuilder.Entity("SportsApplication.Data.Entity.TestList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("date");

                    b.Property<int>("participant_num");

                    b.Property<string>("test_type");

                    b.HasKey("id");

                    b.ToTable("TestLists");
                });
#pragma warning restore 612, 618
        }
    }
}
